version: '3.4'

services:
  backend:
    image: ${IMAGE_REGISTRY:-docker.io}/rikkenbacker620/svp-backend-new
    build:
      context: ./backend
      target: dev
    env_file:
      - .env
    ports:
      - 8999:8000
    volumes:
      - ./backend:/backend
    networks:
      - public
    extra_hosts:
      - "host.docker.internal:host-gateway"

  frontend:
    image: ${IMAGE_REGISTRY:-docker.io}/rikkenbacker620/svp-frontend-new
    build:
      context: ./frontend
      target: dev
    ports:
      - 80:80
      - 12333:3232
    volumes:
      - ./frontend:/frontend
    networks:
      - public
    depends_on:
      - backend

  codeanalyze:
    image: ${IMAGE_REGISTRY:-docker.io}/rikkenbacker620/svp-codeanalyze
    ports:
      - 9000:9000
    build:
      context: ./codeanalyze
    networks:
      - public

  codegraph:
    image: ${IMAGE_REGISTRY:-docker.io}/rikkenbacker620/svp-codegraph
    ports:
      - 3000:80
    build:
      context: ./codegraph
    networks:
      - public
networks:
  public:


