version: '3.4'

services:
  backend:
    build:
      context: ./backend
    ports:
      - 12357:12355
    env_file:
      - .deploy.env
    extra_hosts:
      - "host.docker.internal:host-gateway"

  frontend:
    build:
      context: ./frontend
    ports:
      - 80:80
    env_file:
      - .deploy.env
    depends_on:
      - backend