version: '3.4'

services:
  backend:
    build:
      context: ./backend
    ports:
      - 12357:12355
    env_file:
      - .deploy.env
    networks:
      - public
    extra_hosts:
      - "host.docker.internal:host-gateway"

  frontend:
    build:
      context: ./frontend
    ports:
      - 80:80
    networks:
      - public
    depends_on:
      - backend
    tty: true

networks:
  public:


