version: '3.4'

services:
  backend:
    image: ${IMAGE_REGISTRY:-docker.io}/rikkenbacker620/svp-backend
    build:
      context: ./backend
    networks:
      - public
    extra_hosts:
      - "host.docker.internal:host-gateway"

  frontend:
    image: ${IMAGE_REGISTRY:-docker.io}/rikkenbacker620/svp-frontend
    build:
      context: ./frontend
    ports:
      - 80:80
    networks:
      - public
    depends_on:
      - backend

networks:
  public:


