on: [push, workflow_dispatch]
name: Aliyun Deploy

env:
    IMAGE_REGISTRY: registry.cn-shanghai.aliyuncs.com

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: "Checkout GitHub Action"
              uses: actions/checkout@main

            - name: "Build and push image"
              uses: azure/docker-login@v1
              with:
                  login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
                  username: ${{ secrets.REGISTRY_USERNAME }}
                  password: ${{ secrets.REGISTRY_PASSWORD }}
            - run: |
                  docker-compose build
                  docker-compose push
