on: [push, workflow_dispatch]
name: Aliyun Deploy

env:
    IMAGE_REGISTRY: registry.cn-shanghai.aliyuncs.com

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: "Checkout GitHub Action"
              uses: actions/checkout@v2

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1

            - name: Login to DockerHub
              uses: docker/login-action@v1
              with:
                  registry: ${{ env.IMAGE_REGISTRY }}
                  username: ${{ secrets.REGISTRY_USERNAME }}
                  password: ${{ secrets.REGISTRY_PASSWORD }}

            - name: Build frontend
              uses: docker/build-push-action@v2
              with:
                  context: ./frontend
                  push: true
                  tags: ${{ env.IMAGE_REGISTRY }}/rikkenbacker620/svp-frontend
                  cache-from: type=registry,ref=${{ env.IMAGE_REGISTRY }}/rikkenbacker620/svp-frontend
                  cache-to: type=inline

            - name: Build backend
              uses: docker/build-push-action@v2
              with:
                  context: ./backend
                  push: true
                  tags: ${{ env.IMAGE_REGISTRY }}/rikkenbacker620/svp-backend
                  cache-from: type=registry,ref=${{ env.IMAGE_REGISTRY }}/rikkenbacker620/svp-backend
                  cache-to: type=inline